function withAlpha(hex, alpha) {
  if (typeof hex !== "string" || !hex.startsWith("#") || hex.length !== 7) {
    return hex;
  }
  return `${hex}${alpha}`;
}

function makeTokenColor(name, scope, foreground, fontStyle, background) {
  const settings = {};
  if (foreground) settings.foreground = foreground;
  if (fontStyle) settings.fontStyle = fontStyle;
  if (background) settings.background = background;
  return { name, scope, settings };
}

function keyMatchesFamily(key, family) {
  return key === family || key.startsWith(`${family}.`);
}

function pruneColors(colors) {
  const requiredFamilies = [
    "activityBarBadge",
    "badge",
    "banner",
    "button",
    "checkbox",
    "debugToolBar",
    "descriptionForeground",
    "dropdown",
    "input",
    "list",
    "menu",
    "menubar",
    "panel",
    "panelSectionHeader",
    "peekView",
    "scrollbar",
    "settings",
    "statusBar",
    "statusBarItem",
    "editorGroupHeader",
    "editorGutter",
    "editorHoverWidget",
    "editorSuggestWidget",
    "editorOverviewRuler",
    "editorRuler",
    "editorWhitespace",
    "editorBracketHighlight",
    "editorBracketMatch",
    "editorBracketPairGuide",
    "minimapGutter",
    "sideBarSectionHeader",
    "titleBar",
    "toolbar",
    "window",
    "diffEditor",
    "gitDecoration",
    "textLink",
    "textBlockQuote",
    "textPreformat",
  ];

  const preferredFamilies = [
    "foreground",
    "focusBorder",
    "errorForeground",
    "icon",
    "selection",
    "widget",
    "progressBar",
    "activityBar",
    "sideBar",
    "sideBarTitle",
    "editorGroup",
    "tab",
    "editor",
    "editorLineNumber",
    "editorCursor",
    "editorIndentGuide",
    "statusBar",
    "terminal",
    "terminalCursor",
  ];

  const maxKeys = 199;
  const entries = Object.entries(colors);
  const include = new Set();

  for (const [key] of entries) {
    if (requiredFamilies.some((family) => keyMatchesFamily(key, family))) {
      include.add(key);
    }
  }

  for (const [key] of entries) {
    if (include.size >= maxKeys) break;
    if (preferredFamilies.some((family) => keyMatchesFamily(key, family))) {
      include.add(key);
    }
  }

  return Object.fromEntries(entries.filter(([key]) => include.has(key)));
}

export function buildVSCodeTheme({ variant, paletteMap, tokenMap, palette }) {
  const isDark = variant === "night";

  const c = {
    bg0: paletteMap.karasuBg0,
    bg1: paletteMap.karasuBg1,
    bg2: paletteMap.karasuBg2,
    bg3: paletteMap.karasuBg3,
    bg4: paletteMap.karasuBg4,
    visual: paletteMap.karasuBgVisual,
    search: paletteMap.karasuBgSearch,
    fg0: paletteMap.karasuFg0,
    fg1: paletteMap.karasuFg1,
    fg2: paletteMap.karasuFg2,
    fg3: paletteMap.karasuFg3,
    dim: paletteMap.karasuFgDim,
    red: tokenMap.diagError,
    green: paletteMap.karasuGreen,
    yellow: paletteMap.karasuYellow,
    blue: paletteMap.karasuBlue,
    purple: paletteMap.karasuPurple,
    aqua: paletteMap.karasuAqua,
    orange: paletteMap.karasuOrange,
    brightRed: paletteMap.karasuBrightRed,
    brightGreen: paletteMap.karasuBrightGreen,
    brightYellow: paletteMap.karasuBrightYellow,
    brightBlue: paletteMap.karasuBrightBlue,
    brightMagenta: paletteMap.karasuBrightMagenta,
    brightCyan: paletteMap.karasuBrightCyan,
    brightWhite: paletteMap.karasuBrightWhite,
    commentRole: tokenMap.syntaxComment,
    keywordRole: tokenMap.syntaxKeyword,
    typeRole: tokenMap.syntaxType,
    functionRole: tokenMap.syntaxFunction,
    stringRole: tokenMap.syntaxString,
    numberRole: tokenMap.syntaxNumber,
    operatorRole: tokenMap.syntaxOperator,
    propertyRole: tokenMap.syntaxProperty,
    variableRole: tokenMap.syntaxVariable,
    punctuationRole: tokenMap.syntaxPunctuation,
    linkRole: tokenMap.syntaxLink,
    error: tokenMap.diagError,
    warning: tokenMap.diagWarning,
    info: tokenMap.diagInfo,
    hint: tokenMap.diagHint,
    cursor: tokenMap.cursor,
    cursorText: tokenMap.cursorText,
    selection: tokenMap.selectionBg,
    selectionFg: tokenMap.selectionFg,
    searchBg: tokenMap.searchBg,
    searchFg: tokenMap.searchFg,
    diffAdd: tokenMap.diffAddedBg,
    diffRemove: tokenMap.diffRemovedBg,
    diffContext: tokenMap.diffContextBg,
    errorBg: tokenMap.errorBg,
    warningBg: tokenMap.warningBg,
    infoBg: tokenMap.infoBg,
    hintBg: tokenMap.hintBg,
  };

  const colors = {
    foreground: c.fg0,
    descriptionForeground: c.fg2,
    focusBorder: c.bg4,
    errorForeground: c.error,
    "icon.foreground": c.fg2,
    "textLink.foreground": c.linkRole,
    "textLink.activeForeground": c.brightBlue,
    "textBlockQuote.background": c.bg1,
    "textBlockQuote.border": c.bg3,
    "textPreformat.foreground": c.operatorRole,
    "textCodeBlock.background": c.bg1,
    "widget.shadow": withAlpha(c.bg0, "88"),
    "selection.background": withAlpha(c.selection, "cc"),

    "button.background": c.bg2,
    "button.foreground": c.fg0,
    "button.hoverBackground": c.bg3,
    "button.secondaryBackground": c.bg3,
    "button.secondaryForeground": c.fg0,
    "button.secondaryHoverBackground": c.bg4,
    "button.separator": c.bg4,
    "button.border": c.bg3,

    "checkbox.background": c.bg1,
    "checkbox.foreground": c.typeRole,
    "checkbox.border": c.bg3,

    "dropdown.background": c.bg1,
    "dropdown.foreground": c.fg0,
    "dropdown.border": c.bg3,

    "input.background": c.bg1,
    "input.foreground": c.fg0,
    "input.border": c.bg3,
    "input.placeholderForeground": c.fg3,
    "inputOption.activeBorder": c.propertyRole,
    "inputValidation.errorBackground": withAlpha(c.error, "55"),
    "inputValidation.errorForeground": c.fg0,
    "inputValidation.errorBorder": c.error,
    "inputValidation.infoBackground": withAlpha(c.info, "55"),
    "inputValidation.infoForeground": c.fg0,
    "inputValidation.infoBorder": c.info,
    "inputValidation.warningBackground": withAlpha(c.warning, "55"),
    "inputValidation.warningForeground": c.fg0,
    "inputValidation.warningBorder": c.warning,

    "scrollbar.shadow": withAlpha(c.bg0, "aa"),
    "scrollbarSlider.background": withAlpha(c.fg3, "66"),
    "scrollbarSlider.hoverBackground": withAlpha(c.fg2, "88"),
    "scrollbarSlider.activeBackground": withAlpha(c.fg1, "aa"),

    "badge.background": c.bg2,
    "badge.foreground": c.fg0,
    "progressBar.background": c.brightGreen,

    "list.activeSelectionBackground": withAlpha(c.bg3, "cc"),
    "list.activeSelectionForeground": c.fg0,
    "list.inactiveSelectionBackground": withAlpha(c.bg2, "cc"),
    "list.inactiveSelectionForeground": c.fg1,
    "list.dropBackground": withAlpha(c.bg2, "cc"),
    "list.focusBackground": withAlpha(c.bg3, "cc"),
    "list.focusForeground": c.fg0,
    "list.inactiveFocusBackground": withAlpha(c.bg2, "cc"),
    "list.hoverBackground": withAlpha(c.bg2, "99"),
    "list.hoverForeground": c.fg0,
    "list.highlightForeground": c.brightBlue,
    "list.errorForeground": c.error,
    "list.warningForeground": c.warning,
    "tree.indentGuidesStroke": c.bg4,

    "activityBar.background": c.bg1,
    "activityBar.foreground": c.fg0,
    "activityBar.inactiveForeground": c.fg3,
    "activityBar.border": c.bg1,
    "activityBar.dropBackground": withAlpha(c.bg2, "cc"),
    "activityBarBadge.background": c.bg3,
    "activityBarBadge.foreground": c.fg0,
    "activityBar.activeBorder": c.typeRole,
    "activityBar.activeFocusBorder": c.typeRole,

    "sideBar.background": c.bg1,
    "sideBar.foreground": c.fg1,
    "sideBar.border": c.bg1,
    "sideBarTitle.foreground": c.fg0,
    "sideBarSectionHeader.background": c.bg1,
    "sideBarSectionHeader.foreground": c.fg1,

    "minimap.findMatchHighlight": withAlpha(c.searchBg, "aa"),
    "minimap.selectionHighlight": withAlpha(c.selection, "cc"),
    "minimap.errorHighlight": withAlpha(c.error, "aa"),
    "minimap.warningHighlight": withAlpha(c.warning, "aa"),
    "minimapGutter.addedBackground": withAlpha(c.green, "aa"),
    "minimapGutter.modifiedBackground": withAlpha(c.propertyRole, "aa"),
    "minimapGutter.deletedBackground": withAlpha(c.error, "aa"),

    "editorGroup.border": c.bg3,
    "editorGroup.dropBackground": withAlpha(c.bg2, "cc"),
    "editorGroupHeader.tabsBackground": c.bg1,
    "editorGroupHeader.noTabsBackground": c.bg1,

    "tab.border": c.bg1,
    "tab.activeBackground": c.bg2,
    "tab.activeForeground": c.fg0,
    "tab.inactiveBackground": c.bg1,
    "tab.inactiveForeground": c.fg2,
    "tab.hoverBackground": c.bg2,
    "tab.hoverForeground": c.fg0,
    "tab.unfocusedActiveForeground": c.fg1,
    "tab.unfocusedInactiveForeground": c.fg3,
    "tab.unfocusedHoverForeground": c.fg1,
    "tab.activeBorder": c.typeRole,
    "tab.activeBorderTop": c.typeRole,
    "tab.unfocusedActiveBorder": c.fg3,
    "tab.lastPinnedBorder": c.bg3,

    "editor.background": c.bg0,
    "editor.foreground": c.fg0,
    "editorLineNumber.foreground": c.fg3,
    "editorLineNumber.activeForeground": c.typeRole,
    "editorCursor.foreground": c.cursor,
    "editorCursor.background": c.cursorText,
    "editor.selectionBackground": c.selection,
    "editor.selectionForeground": c.selectionFg,
    "editor.selectionHighlightBackground": withAlpha(c.selection, "77"),
    "editor.inactiveSelectionBackground": withAlpha(c.selection, "66"),
    "editor.wordHighlightBackground": withAlpha(c.visual, "66"),
    "editor.wordHighlightStrongBackground": withAlpha(c.visual, "aa"),
    "editor.hoverHighlightBackground": withAlpha(c.bg2, "aa"),
    "editor.findMatchBackground": c.searchBg,
    "editor.findMatchBorder": c.typeRole,
    "editor.findMatchHighlightBackground": withAlpha(c.searchBg, "66"),
    "editor.findRangeHighlightBackground": withAlpha(c.bg2, "aa"),
    "editor.lineHighlightBackground": c.bg1,
    "editor.lineHighlightBorder": withAlpha(c.bg1, "00"),
    "editor.rangeHighlightBackground": withAlpha(c.bg2, "77"),
    "editor.symbolHighlightBackground": withAlpha(c.propertyRole, "44"),
    "editorWhitespace.foreground": c.bg3,
    "editorIndentGuide.background": withAlpha(c.fg3, "33"),
    "editorIndentGuide.activeBackground": withAlpha(c.fg2, "66"),
    "editorIndentGuide.background1": withAlpha(c.fg3, "33"),
    "editorIndentGuide.activeBackground1": withAlpha(c.fg2, "66"),
    "editorRuler.foreground": withAlpha(c.fg3, "88"),
    "editorCodeLens.foreground": c.fg3,
    "editor.foldBackground": withAlpha(c.bg2, "88"),
    "editorLink.activeForeground": c.linkRole,
    "editorBracketMatch.background": withAlpha(c.bg3, "aa"),
    "editorBracketMatch.border": withAlpha(c.bg3, "00"),
    "editorBracketHighlight.foreground1": c.keywordRole,
    "editorBracketHighlight.foreground2": c.typeRole,
    "editorBracketHighlight.foreground3": c.green,
    "editorBracketHighlight.foreground4": c.propertyRole,
    "editorBracketHighlight.foreground5": c.operatorRole,
    "editorBracketHighlight.foreground6": c.numberRole,
    "editorBracketHighlight.unexpectedBracket.foreground": c.error,
    "editorBracketPairGuide.activeBackground1": c.keywordRole,
    "editorBracketPairGuide.activeBackground2": c.typeRole,
    "editorBracketPairGuide.activeBackground3": c.green,
    "editorBracketPairGuide.activeBackground4": c.propertyRole,
    "editorBracketPairGuide.activeBackground5": c.operatorRole,
    "editorBracketPairGuide.activeBackground6": c.numberRole,
    "editorBracketPairGuide.background1": withAlpha(c.keywordRole, "44"),
    "editorBracketPairGuide.background2": withAlpha(c.typeRole, "44"),
    "editorBracketPairGuide.background3": withAlpha(c.green, "44"),
    "editorBracketPairGuide.background4": withAlpha(c.propertyRole, "44"),
    "editorBracketPairGuide.background5": withAlpha(c.operatorRole, "44"),
    "editorBracketPairGuide.background6": withAlpha(c.numberRole, "44"),

    "editorOverviewRuler.border": withAlpha(c.bg0, "00"),
    "editorOverviewRuler.findMatchForeground": c.searchBg,
    "editorOverviewRuler.rangeHighlightForeground": c.propertyRole,
    "editorOverviewRuler.selectionHighlightForeground": c.selection,
    "editorOverviewRuler.wordHighlightForeground": c.visual,
    "editorOverviewRuler.wordHighlightStrongForeground": c.fg2,
    "editorOverviewRuler.modifiedForeground": c.propertyRole,
    "editorOverviewRuler.addedForeground": c.green,
    "editorOverviewRuler.deletedForeground": c.error,
    "editorOverviewRuler.errorForeground": c.error,
    "editorOverviewRuler.warningForeground": c.warning,
    "editorOverviewRuler.infoForeground": c.info,

    "editorError.foreground": c.error,
    "editorWarning.foreground": c.warning,
    "editorInfo.foreground": c.info,
    "editorHint.foreground": c.hint,
    "editorError.background": c.errorBg,
    "editorWarning.background": c.warningBg,
    "editorInfo.background": c.infoBg,

    "editorGutter.background": withAlpha(c.bg0, "00"),
    "editorGutter.modifiedBackground": c.propertyRole,
    "editorGutter.addedBackground": c.green,
    "editorGutter.deletedBackground": c.error,
    "editorGutter.commentRangeForeground": c.fg3,

    "diffEditor.insertedTextBackground": withAlpha(c.diffAdd, "cc"),
    "diffEditor.removedTextBackground": withAlpha(c.diffRemove, "cc"),
    "diffEditor.diagonalFill": c.diffContext,
    "diffEditor.insertedLineBackground": withAlpha(c.diffAdd, "88"),
    "diffEditor.removedLineBackground": withAlpha(c.diffRemove, "88"),

    "editorSuggestWidget.background": c.bg1,
    "editorSuggestWidget.foreground": c.fg0,
    "editorSuggestWidget.highlightForeground": c.propertyRole,
    "editorSuggestWidget.selectedBackground": c.bg2,
    "editorSuggestWidget.border": c.bg3,

    "editorWidget.background": c.bg1,
    "editorWidget.foreground": c.fg0,
    "editorWidget.border": c.bg3,
    "editorHoverWidget.background": c.bg1,
    "editorHoverWidget.border": c.bg3,
    "editorMarkerNavigation.background": c.bg1,
    "editorMarkerNavigationError.background": c.errorBg,
    "editorMarkerNavigationWarning.background": c.warningBg,
    "editorMarkerNavigationInfo.background": c.infoBg,

    "peekView.border": c.bg3,
    "peekViewEditor.background": c.bg1,
    "peekViewEditor.matchHighlightBackground": withAlpha(c.searchBg, "88"),
    "peekViewEditorGutter.background": c.bg1,
    "peekViewResult.background": c.bg1,
    "peekViewResult.matchHighlightBackground": withAlpha(c.searchBg, "66"),
    "peekViewResult.selectionBackground": c.bg2,
    "peekViewTitle.background": c.bg2,
    "peekViewTitleDescription.foreground": c.fg3,
    "peekViewTitleLabel.foreground": c.fg1,

    "panel.background": c.bg1,
    "panel.border": c.bg3,
    "panelSection.border": c.bg3,
    "panelSection.dropBackground": withAlpha(c.bg2, "cc"),
    "panelSectionHeader.background": c.bg1,
    "panelSectionHeader.foreground": c.fg1,
    "panelTitle.activeBorder": c.typeRole,
    "panelTitle.activeForeground": c.fg0,
    "panelTitle.inactiveForeground": c.fg3,
    "panelInput.border": c.bg3,

    "statusBar.background": c.bg1,
    "statusBar.foreground": c.fg1,
    "statusBar.border": c.bg1,
    "statusBar.debuggingBackground": c.error,
    "statusBar.debuggingForeground": c.fg0,
    "statusBar.debuggingBorder": c.bg3,
    "statusBar.noFolderBackground": c.bg1,
    "statusBar.noFolderForeground": c.fg1,
    "statusBar.noFolderBorder": c.bg1,
    "statusBarItem.hoverBackground": c.bg2,
    "statusBarItem.prominentBackground": c.bg2,
    "statusBarItem.prominentForeground": c.fg0,
    "statusBarItem.prominentHoverBackground": c.bg3,
    "statusBarItem.remoteBackground": c.propertyRole,
    "statusBarItem.remoteForeground": c.fg0,

    "titleBar.activeBackground": c.bg1,
    "titleBar.activeForeground": c.fg1,
    "titleBar.inactiveBackground": c.bg1,
    "titleBar.inactiveForeground": c.fg3,
    "titleBar.border": c.bg1,

    "menu.background": c.bg1,
    "menu.foreground": c.fg0,
    "menu.border": c.bg3,
    "menu.selectionBackground": c.bg2,
    "menu.selectionForeground": c.fg0,
    "menu.separatorBackground": c.bg3,
    "menubar.selectionBackground": c.bg2,
    "menubar.selectionForeground": c.fg0,
    "menubar.selectionBorder": c.bg3,

    "notificationCenterHeader.background": c.bg1,
    "notificationCenterHeader.foreground": c.fg1,
    "notifications.background": c.bg1,
    "notifications.foreground": c.fg0,
    "notifications.border": c.bg3,
    "notificationsErrorIcon.foreground": c.error,
    "notificationsWarningIcon.foreground": c.warning,
    "notificationsInfoIcon.foreground": c.info,
    "notificationLink.foreground": c.linkRole,

    "pickerGroup.border": c.bg3,
    "pickerGroup.foreground": c.fg2,
    "quickInput.background": c.bg1,
    "quickInput.foreground": c.fg0,
    "quickInputList.focusBackground": c.bg2,
    "quickInputTitle.background": c.bg1,

    "gitDecoration.addedResourceForeground": c.green,
    "gitDecoration.modifiedResourceForeground": c.propertyRole,
    "gitDecoration.deletedResourceForeground": c.error,
    "gitDecoration.untrackedResourceForeground": c.functionRole,
    "gitDecoration.ignoredResourceForeground": c.fg3,
    "gitDecoration.conflictingResourceForeground": c.operatorRole,
    "gitDecoration.submoduleResourceForeground": c.numberRole,

    "terminal.background": c.bg0,
    "terminal.foreground": c.fg0,
    "terminal.border": c.bg3,
    "terminal.selectionBackground": c.selection,
    "terminalCursor.foreground": c.cursor,
    "terminalCursor.background": c.cursorText,
    "terminal.ansiBlack": palette.ansi.normal.black,
    "terminal.ansiRed": palette.ansi.normal.red,
    "terminal.ansiGreen": palette.ansi.normal.green,
    "terminal.ansiYellow": palette.ansi.normal.yellow,
    "terminal.ansiBlue": palette.ansi.normal.blue,
    "terminal.ansiMagenta": palette.ansi.normal.magenta,
    "terminal.ansiCyan": palette.ansi.normal.cyan,
    "terminal.ansiWhite": palette.ansi.normal.white,
    "terminal.ansiBrightBlack": palette.ansi.bright.black,
    "terminal.ansiBrightRed": palette.ansi.bright.red,
    "terminal.ansiBrightGreen": palette.ansi.bright.green,
    "terminal.ansiBrightYellow": palette.ansi.bright.yellow,
    "terminal.ansiBrightBlue": palette.ansi.bright.blue,
    "terminal.ansiBrightMagenta": palette.ansi.bright.magenta,
    "terminal.ansiBrightCyan": palette.ansi.bright.cyan,
    "terminal.ansiBrightWhite": palette.ansi.bright.white,

    "banner.background": c.bg1,
    "banner.foreground": c.fg1,
    "banner.iconForeground": c.typeRole,
    "debugToolBar.background": c.bg1,
    "debugToolBar.border": c.bg3,
    "toolbar.hoverBackground": c.bg2,

    "settings.headerForeground": c.fg1,
    "settings.focusedRowBackground": c.bg2,
    "settings.rowHoverBackground": withAlpha(c.bg2, "66"),
    "settings.modifiedItemIndicator": c.warning,

    "window.activeBorder": c.bg3,
    "window.inactiveBorder": c.bg2,

    "breadcrumb.background": c.bg1,
    "breadcrumb.foreground": c.fg2,
    "breadcrumb.focusForeground": c.fg0,
    "breadcrumb.activeSelectionForeground": c.fg0,
    "breadcrumbPicker.background": c.bg1,

    "walkThrough.embeddedEditorBackground": c.bg1,
    "walkThrough.stepTitle.foreground": c.fg0,

    "editorInlayHint.foreground": c.fg3,
    "editorInlayHint.background": withAlpha(c.bg1, "00"),
    "editorInlayHint.typeForeground": c.fg2,
    "editorInlayHint.typeBackground": withAlpha(c.bg1, "00"),
    "editorInlayHint.parameterForeground": c.fg3,
    "editorInlayHint.parameterBackground": withAlpha(c.bg1, "00"),

    "problemsErrorIcon.foreground": c.error,
    "problemsWarningIcon.foreground": c.warning,
    "problemsInfoIcon.foreground": c.info,

    "debugConsole.errorForeground": c.error,
    "debugConsole.warningForeground": c.warning,
    "debugConsole.infoForeground": c.info,
    "debugConsole.sourceForeground": c.fg2,
    "debugConsoleInputIcon.foreground": c.propertyRole,

    "extensionButton.prominentBackground": c.bg2,
    "extensionButton.prominentForeground": c.fg0,
    "extensionButton.prominentHoverBackground": c.bg3,

    "testing.iconPassed": c.green,
    "testing.iconQueued": c.warning,
    "testing.iconFailed": c.error,
    "testing.iconSkipped": c.fg3,
    "testing.peekBorder": c.bg3,
    "testing.peekHeaderBackground": c.bg1,

    "merge.currentHeaderBackground": withAlpha(c.propertyRole, "55"),
    "merge.currentContentBackground": withAlpha(c.propertyRole, "33"),
    "merge.incomingHeaderBackground": withAlpha(c.green, "55"),
    "merge.incomingContentBackground": withAlpha(c.green, "33"),
    "merge.commonHeaderBackground": withAlpha(c.warning, "55"),
    "merge.commonContentBackground": withAlpha(c.warning, "33"),
    "merge.border": c.bg3,

    "minimap.background": c.bg0,
    "minimap.selectionOccurrenceHighlight": withAlpha(c.visual, "aa"),
    "minimap.selectionOccurrenceHighlightBorder": withAlpha(c.visual, "00"),
  };

  const tokenColors = [
    makeTokenColor("Comment", ["comment", "punctuation.definition.comment"], c.commentRole, "italic"),
    makeTokenColor("Comment TODO", ["comment.keyword", "comment.block.documentation keyword"], c.warning, "bold"),
    makeTokenColor("String", ["string", "meta.embedded.assembly"], c.stringRole),
    makeTokenColor("String Escapes", ["constant.character.escape", "string.regexp"], c.operatorRole),
    makeTokenColor("String Interpolation", ["punctuation.definition.template-expression", "punctuation.section.embedded"], c.operatorRole),
    makeTokenColor("Regex Character Class", ["constant.other.character-class.set.regexp", "keyword.operator.quantifier.regexp"], c.operatorRole),
    makeTokenColor("Number", ["constant.numeric", "constant.language.boolean"], c.numberRole),
    makeTokenColor("Constant", ["constant.language", "constant.character", "variable.other.constant"], c.numberRole),
    makeTokenColor("Keyword", ["keyword", "storage.type", "storage.modifier"], c.keywordRole),
    makeTokenColor("Control Flow", ["keyword.control", "keyword.control.flow"], c.keywordRole, "italic"),
    makeTokenColor("Operators", ["keyword.operator", "punctuation.separator", "meta.brace"], c.operatorRole),
    makeTokenColor("Punctuation", ["punctuation", "meta.delimiter"], c.punctuationRole),
    makeTokenColor("Function", ["entity.name.function", "support.function", "meta.function-call"], c.functionRole),
    makeTokenColor("Method", ["entity.name.function.member", "variable.function"], c.functionRole),
    makeTokenColor("Type", ["entity.name.type", "support.type", "meta.type"], c.typeRole),
    makeTokenColor("Class", ["entity.name.class", "entity.other.inherited-class"], c.typeRole),
    makeTokenColor("Interface", ["entity.name.type.interface", "entity.name.namespace"], c.typeRole),
    makeTokenColor("Enum", ["entity.name.type.enum", "variable.other.enummember"], c.typeRole),
    makeTokenColor("Variable", ["variable", "identifier"], c.variableRole),
    makeTokenColor("Parameter", ["variable.parameter", "meta.parameter"], c.variableRole),
    makeTokenColor("Property", ["variable.other.property", "support.variable.property"], c.propertyRole),
    makeTokenColor("Builtin Variable", ["support.variable", "variable.language"], c.numberRole),
    makeTokenColor("Module", ["support.module", "entity.name.module"], c.typeRole),
    makeTokenColor("Tag Name", ["entity.name.tag", "meta.tag.sgml"], c.operatorRole),
    makeTokenColor("Tag Punctuation", ["punctuation.definition.tag", "punctuation.separator.key-value.html"], c.punctuationRole),
    makeTokenColor("Attribute Name", ["entity.other.attribute-name", "meta.attribute"], c.propertyRole),
    makeTokenColor("Attribute Value", ["string.quoted.double.html", "string.quoted.single.html"], c.stringRole),
    makeTokenColor("JSON Key", ["support.type.property-name.json", "meta.object-literal.key"], c.propertyRole),
    makeTokenColor("JSON Punctuation", ["source.json punctuation", "source.json meta.structure.dictionary.value"], c.punctuationRole),
    makeTokenColor("YAML Key", ["entity.name.tag.yaml", "meta.object.mapping.key.yaml"], c.propertyRole),
    makeTokenColor("YAML Anchor", ["constant.other.reference.link.yaml", "entity.name.type.anchor.yaml"], c.typeRole),
    makeTokenColor("Markdown Heading", ["markup.heading", "entity.name.section"], c.typeRole, "bold"),
    makeTokenColor("Markdown Quote", ["markup.quote", "punctuation.definition.quote.begin.markdown"], c.commentRole, "italic"),
    makeTokenColor("Markdown Bold", ["markup.bold", "punctuation.definition.bold"], c.operatorRole, "bold"),
    makeTokenColor("Markdown Italic", ["markup.italic", "punctuation.definition.italic"], c.keywordRole, "italic"),
    makeTokenColor("Markdown Inline Code", ["markup.inline.raw", "markup.raw.inline"], c.stringRole),
    makeTokenColor("Markdown Link", ["markup.underline.link", "string.other.link.description"], c.linkRole, "underline"),
    makeTokenColor("Markdown List", ["punctuation.definition.list.begin.markdown", "markup.list"], c.operatorRole),
    makeTokenColor("Diff Added", ["markup.inserted", "meta.diff.header.from-file"], c.functionRole),
    makeTokenColor("Diff Removed", ["markup.deleted", "meta.diff.header.to-file"], c.error),
    makeTokenColor("Diff Changed", ["markup.changed", "meta.diff.range"], c.warning),
    makeTokenColor("Invalid", ["invalid", "invalid.illegal"], c.error),
    makeTokenColor("Error", ["error", "token.error-token"], c.error),
    makeTokenColor("Warning", ["warning", "token.warn-token"], c.warning),
    makeTokenColor("Annotation", ["storage.type.annotation", "punctuation.definition.annotation"], c.operatorRole),
    makeTokenColor("Decorator", ["meta.decorator", "entity.name.function.decorator"], c.operatorRole),
    makeTokenColor("JS Arrow", ["storage.type.function.arrow", "keyword.operator.expression.typeof"], c.operatorRole),
    makeTokenColor("JS This", ["variable.language.this", "variable.language.super"], c.variableRole),
    makeTokenColor("TS Generic", ["entity.name.type.type-parameter", "meta.type.parameters"], c.typeRole),
    makeTokenColor("TS Namespace", ["entity.name.namespace.ts", "support.type.namespace.ts"], c.typeRole),
    makeTokenColor("Python Self", ["variable.parameter.function.language.special.self.python", "variable.language.special.self.python"], c.variableRole),
    makeTokenColor("Python Dunder", ["support.variable.magic.python", "entity.name.function.magic.python"], c.variableRole),
    makeTokenColor("Rust Macro", ["entity.name.function.macro.rust", "support.function.macro.rust"], c.operatorRole),
    makeTokenColor("Rust Lifetime", ["entity.name.type.lifetime.rust", "storage.modifier.lifetime.rust"], c.typeRole),
    makeTokenColor("Lua Global", ["support.variable.lua", "variable.other.lua"], c.variableRole),
    makeTokenColor("Lua Function", ["entity.name.function.lua", "support.function.lua"], c.functionRole),
    makeTokenColor("Shell Variable", ["variable.other.readwrite.shell", "variable.parameter.positional.shell"], c.variableRole),
    makeTokenColor("Shell Command", ["support.function.builtin.shell", "entity.name.command.shell"], c.functionRole),
    makeTokenColor("CSS Property", ["support.type.property-name.css", "meta.property-name.css"], c.propertyRole),
    makeTokenColor("CSS Value", ["support.constant.property-value.css", "meta.property-value.css"], c.stringRole),
    makeTokenColor("CSS Class", ["entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css"], c.typeRole),
    makeTokenColor("SQL Keyword", ["keyword.other.DML.sql", "keyword.other.sql"], c.keywordRole),
    makeTokenColor("SQL Table", ["entity.name.type.table.sql", "support.class.table.sql"], c.typeRole),
    makeTokenColor("SQL Column", ["entity.name.type.column.sql", "variable.other.object.column.sql"], c.propertyRole),
    makeTokenColor("Doc Tag", ["storage.type.class.jsdoc", "entity.name.type.instance.jsdoc"], c.operatorRole),
    makeTokenColor("Doc Description", ["comment.block.documentation", "comment.block.documentation variable"], c.commentRole),
    makeTokenColor("Punctuation Brackets", ["punctuation.section.block", "punctuation.section.group"], c.punctuationRole),
    makeTokenColor("Punctuation Parameters", ["punctuation.definition.parameters", "punctuation.separator.parameter"], c.punctuationRole),
    makeTokenColor("Punctuation Array", ["meta.brace.square", "punctuation.definition.array"], c.punctuationRole),
    makeTokenColor("Punctuation Object", ["meta.brace.curly", "punctuation.definition.block"], c.punctuationRole),
    makeTokenColor("Meta Import", ["meta.import", "keyword.control.import"], c.keywordRole),
    makeTokenColor("Meta Export", ["meta.export", "keyword.control.export"], c.keywordRole),
    makeTokenColor("Meta Embedded", ["meta.embedded", "source.embedded"], c.variableRole),
    makeTokenColor("Markup Raw Block", ["markup.fenced_code.block", "markup.raw.block"], c.stringRole, null, withAlpha(c.bg1, "66")),
    makeTokenColor("Link URL", ["markup.underline.link.image", "meta.link.inline punctuation.definition.string.begin"], c.linkRole, "underline"),
    makeTokenColor("Quote Punctuation", ["punctuation.definition.blockquote.markdown", "punctuation.definition.quote"], c.punctuationRole),
    makeTokenColor("Template String Punctuation", ["string.template punctuation.definition.string.template", "meta.template.expression punctuation"], c.operatorRole),
    makeTokenColor("Escape Punctuation", ["punctuation.definition.escape", "constant.character.escape.backslash"], c.operatorRole),
    makeTokenColor("Heading Marker", ["punctuation.definition.heading.markdown", "markup.heading.setext.1.markdown"], c.typeRole, "bold"),
    makeTokenColor("Emphasis Marker", ["punctuation.definition.emphasis.markdown", "punctuation.definition.strong.markdown"], c.keywordRole),
    makeTokenColor("Deleted Punctuation", ["punctuation.definition.deleted", "markup.deleted.git_gutter"], c.error),
    makeTokenColor("Inserted Punctuation", ["punctuation.definition.inserted", "markup.inserted.git_gutter"], c.functionRole),
  ];

  const semanticTokenColors = {
    namespace: c.typeRole,
    class: c.typeRole,
    interface: c.typeRole,
    enum: c.typeRole,
    typeParameter: c.typeRole,
    property: c.propertyRole,
    variable: c.variableRole,
    parameter: c.variableRole,
    function: c.functionRole,
    method: c.functionRole,
    macro: c.operatorRole,
    "keyword.controlFlow": c.keywordRole,
    "variable.readonly": c.numberRole,
    "variable.defaultLibrary": c.numberRole,
    "property.defaultLibrary": c.numberRole,
    operator: c.operatorRole,
  };

  return {
    name: isDark ? "Karasu Night" : "Karasu Snow",
    type: isDark ? "dark" : "light",
    semanticHighlighting: true,
    semanticTokenColors,
    colors: pruneColors(colors),
    tokenColors,
  };
}
